apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: etos-suite-starter
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: suite-starter
  name: etos-suite-starter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etos-suite-starter:sa:job-creator
subjects:
- kind: ServiceAccount
  name: etos-suite-starter
