apiVersion: v1
kind: ServiceAccount
metadata:
  name: etos-suite-starter
  labels:
    app.kubernetes.io/name: etos-suite-starter
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: suite-starter
