apiVersion: v1
kind: ConfigMap
metadata:
  name: etos-suite-runner-template
  labels:
    app.kubernetes.io/name: etos-suite-runner
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: suite-starter
data:
  suite_runner_template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {job_name}
      labels:
        app: suite-runner
        id: {suite_id}
    spec:
      ttlSecondsAfterFinished: {ttl}
      template:
        metadata:
          name: {job_name}
        spec:
          terminationGracePeriodSeconds: {termination_grace_period}
          volumes:
          - name: kubexit
            emptyDir: {{}}
          - name: graveyard
            emptyDir:
              medium: Memory
          initContainers:
          - name: kubexit
            image: karlkfi/kubexit:latest
            command: ["cp", "/bin/kubexit", "/kubexit/kubexit"]
            resources:
              requests:
                memory: "32Mi"
              limits:
                memory: "64Mi"
            volumeMounts:
            - mountPath: /kubexit
              name: kubexit
          - name: create-queue
            image: {log_listener}
            command: ["python", "-u", "-m", "create_queue"]
            resources:
              requests:
                memory: "128Mi"
              limits:
                memory: "256Mi"
            envFrom:
            - configMapRef:
                name: {etos_configmap}
            - secretRef:
                name: {etos_rabbitmq_secret}
            env:
            - name: TERCC
              value: '{EiffelTestExecutionRecipeCollectionCreatedEvent}'
          serviceAccountName: etos-sa
          containers:
          - name: {job_name}
            image: {docker_image}
            imagePullPolicy: Always
            command: ['/kubexit/kubexit']
            args: ['python', '-u', '-m', 'etos_suite_runner']
            resources:
              requests:
                memory: "150Mi"
              limits:
                memory: "300Mi"
            envFrom:
            - configMapRef:
                name: {etos_configmap}
            - secretRef:
                name: {etos_rabbitmq_secret}
            - configMapRef:
                name: {etos_observability_configmap}
            env:
            - name: TERCC
              value: '{EiffelTestExecutionRecipeCollectionCreatedEvent}'
            - name: KUBEXIT_NAME
              value: esr
            - name: KUBEXIT_GRAVEYARD
              value: /graveyard
            - name: OTEL_CONTEXT
              value: {otel_context}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {otel_exporter_otlp_endpoint}
            volumeMounts:
            - name: graveyard
              mountPath: /graveyard
            - name: kubexit
              mountPath: /kubexit
          - name: etos-log-listener
            image: {log_listener}
            imagePullPolicy: Always
            command: ['/kubexit/kubexit']
            args: ['python', '-u', '-m', 'log_listener']
            resources:
              requests:
                memory: "128Mi"
              limits:
                memory: "256Mi"
            envFrom:
            - configMapRef:
                name: {etos_configmap}
            - secretRef:
                name: {etos_rabbitmq_secret}
            env:
            - name: TERCC
              value: '{EiffelTestExecutionRecipeCollectionCreatedEvent}'
            - name: KUBEXIT_NAME
              value: log_listener
            - name: KUBEXIT_GRACE_PERIOD
              value: '400s' # needs to be greater than grace period of the container
            - name: KUBEXIT_GRAVEYARD
              value: /graveyard
            - name: KUBEXIT_DEATH_DEPS
              value: esr
            volumeMounts:
            - name: graveyard
              mountPath: /graveyard
            - name: kubexit
              mountPath: /kubexit
          restartPolicy: Never
      backoffLimit: 0
